name: ci

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: test
        run: pwd; ls -lash; ls -lash ../; git clone github.com/luclu7/dnswebserver .
      -
        name: Docker build
        run: docker build -t luclu7/dnswebserver:latest .
     
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

