name: ci

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Clone repo
        run: git clone https://github.com/luclu7/dnswebserver .
      -
        name: Docker build
        run: docker build -t luclu7/dnswebserver:latest .
     
      - 
        name: Docker login
        run: docker login --username luclu7 --password ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: push image
        run: docker push luclu7/dnswebserver:latest
