name: ci

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: test
        run: pwd; ls -lash; ls -lash ../
      -
        name: Docker build
        run: docker build -t luclu7/dnswebserver:latest .
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: luclu7/dnswebserver:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

